config/routes.rb
Rails.application.routes.default_url_options[:host] = 'localhost:3000'
Rails.application.routes.draw do
  resources :letter_field_inputs
  resources :letter_requests
  resources :form_field_inputs
  resources :form_text_inputs
  resources :form_field_values
  resources :form_fields
  resources :form_templates
  resources :student_applications
  resources :application_processes
  get 'apply'  => 'apply#index'
  post 'apply'  => 'apply#create'
  get 'apply/:application_process_id/new'  => 'apply#new', as: :apply_to
  get 'letter_requests/fill/:access_code'  => 'letter_requests#fill', as: :fill_letter

end

app/models/letter_request.rb
class LetterRequest < ActiveRecord::Base
  before_save :set_access_code

  has_many :letter_field_inputs, :dependent => :delete_all
  has_many :letter_text_inputs, :dependent => :delete_all
  has_many :letter_file_uploads, :dependent => :delete_all
  belongs_to :student_application

  validates :professor_email, :access_code, presence: true
  validates :access_code, uniqueness: true

  accepts_nested_attributes_for :letter_field_inputs,
                                allow_destroy: true
  accepts_nested_attributes_for :letter_text_inputs,
                                allow_destroy: true
  accepts_nested_attributes_for :letter_file_uploads,
                                allow_destroy: true

  def generate_access_code
    token = SecureRandom.urlsafe_base64
    while LetterRequest.exists?(access_code: token)
      token = SecureRandom.urlsafe_base64
    end
    return token
  end

  def set_access_code
    if !self.access_code?
      self.access_code = generate_access_code
    end
  end

end

app/controllers/letter_requests_controller.rb
class LetterRequestsController < ApplicationController
  before_action :set_letter_request, only: [:show, :edit, :update, :destroy]

  # GET /letter_requests
  # GET /letter_requests.json
  def index
    @letter_requests = LetterRequest.all
  end

  # GET /letter_requests/1
  # GET /letter_requests/1.json
  def show
  end

  # GET /letter_requests/new
  def new
    @letter_request = LetterRequest.new
  end

  # GET /letter_requests/1/edit
  def edit
  end

  def fill
    @letter_request = LetterRequest.find_by_access_code(params[:access_code])
    if !@letter_request.is_filled?
      @letter_fields = FormField.where(form_template_id: @letter_request.student_application.application_process.letter_template_id).where.not(field_type: ['text', 'file'])
      @letter_texts = FormField.where(form_template_id: @letter_request.student_application.application_process.letter_template_id, field_type: 'text' )
      @letter_files = FormField.where(form_template_id: @letter_request.student_application.application_process.letter_template_id, field_type: 'file' )

      @letter_fields.each do |field|
        @letter_request.letter_field_inputs.new(form_field_id: field.id)
      end

      @letter_texts.each do |text|
        @letter_request.letter_text_inputs.new(form_field_id: text.id)
      end

      @letter_files.each do |file|
        @letter_request.letter_file_uploads.new(form_field_id: file.id)
      end
    else
      redirect_to @letter_request, notice: 'Letter already filled.'
    end

  end

  # POST /letter_requests
  # POST /letter_requests.json
  def create
    @letter_request = LetterRequest.new(letter_request_params)

    respond_to do |format|
      if @letter_request.save

        format.html { redirect_to @letter_request, notice: 'Letter request was successfully created.' }
        format.json { render :show, status: :created, location: @letter_request }
      else
        format.html { render :new }
        format.json { render json: @letter_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /letter_requests/1
  # PATCH/PUT /letter_requests/1.json
  def update
    respond_to do |format|
      if @letter_request.update(letter_request_params)
        format.html { redirect_to @letter_request, notice: 'Letter request was successfully updated.' }
        format.json { render :show, status: :ok, location: @letter_request }
      else
        format.html { render :edit }
        format.json { render json: @letter_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /letter_requests/1
  # DELETE /letter_requests/1.json
  def destroy
    @letter_request.destroy
    respond_to do |format|
      format.html { redirect_to letter_requests_url, notice: 'Letter request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_letter_request
      @letter_request = LetterRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def letter_request_params
      params.require(:letter_request).permit(:professor_email, :student_application_id, :access_code, :is_filled,
                                             letter_field_inputs_attributes: [:form_field_id, :input, :_destroy],
                                             letter_text_inputs_attributes: [:id, :letter_request_id, :form_field_id, :input, :_destroy],
                                             letter_file_uploads_attributes:[:id, :letter_request_id, :form_field_id, :file, :_destroy],
      )
    end
end

app/helpers/letter_requests_helper.rb
module LetterRequestsHelper
end

app/views/letter_requests/_form.html.erb
<%= form_for(@letter_request) do |f| %>
  <% if @letter_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@letter_request.errors.count, "error") %> prohibited this letter_request from being saved:</h2>

      <ul>
      <% @letter_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :professor_email %><br>
    <%= f.text_field :professor_email %>
  </div>
  <div class="field">
    <%= f.label :student_application_id %><br>
    <%= f.number_field :student_application_id %>
  </div>
  <div class="field">
    <%= f.label :access_code %><br>
    <%= f.text_field :access_code %>
  </div>
  <div class="field">
    <%= f.label :is_filled %><br>
    <%= f.check_box :is_filled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/letter_requests/edit.html.erb
<h1>Editing Letter Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @letter_request %> |
<%= link_to 'Back', letter_requests_path %>

app/views/letter_requests/fill.html.haml
%h1 Recommendation letter for: #{@letter_request.student_application.student_name}
%h2 Requested to: #{@letter_request.professor_email}

= simple_form_for @letter_request do |f|
  = f.input :is_filled, as: :hidden, input_html: { value: true }
  .nested-fields
    = f.simple_fields_for :letter_field_inputs do |ff|
      = ff.input :form_field_id, as: :hidden, input_html: { value: ff.object.form_field.id }
      - if ff.object.form_field.field_type == 'select'
        = ff.input :input, label: ff.object.form_field.name, :as => :collection_select, collection: FormFieldValue.where(form_field_id: ff.object.form_field.id ),
                    :label_method => :value, :value_method => :value, include_blank: !ff.object.form_field.is_mandatory?
      - elsif ff.object.form_field.field_type == 'radio'
        = ff.input :input, label: ff.object.form_field.name, as: :radio_buttons, collection: FormFieldValue.where(form_field_id: ff.object.form_field.id ),
                    :label_method => :value, :value_method => :value, required: ff.object.form_field.is_mandatory?
      - elsif ff.object.form_field.field_type == 'single_checkbox'
        = ff.input :input, label: ff.object.form_field.name, as: :boolean, checked_value: true, unchecked_value: false
      - elsif ff.object.form_field.field_type == 'collection_checkbox'
        = ff.input :input, label: ff.object.form_field.name, as: :check_boxes, collection: FormFieldValue.where(form_field_id: ff.object.form_field.id ),
                    :label_method => :value, :value_method => :value
      - else
        = ff.input :input, label: ff.object.form_field.name, as: :string, required: ff.object.form_field.is_mandatory?

    = f.simple_fields_for :letter_text_inputs do |ff|
      = ff.input :form_field_id, as: :hidden, input_html: { value: ff.object.form_field.id }
      = ff.input :input, label: ff.object.form_field.name, as: :text, required: ff.object.form_field.is_mandatory?

    = f.simple_fields_for :letter_file_uploads do |ff|
      = ff.input :form_field_id, as: :hidden, input_html: { value: ff.object.form_field.id }
      = ff.input :file, label: ff.object.form_field.name, as: :file

  = f.submit

app/views/letter_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Letter Requests</h1>

<table>
  <thead>
    <tr>
      <th>Professor email</th>
      <th>Student application</th>
      <th>Access code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @letter_requests.each do |letter_request| %>
      <tr>
        <td><%= letter_request.professor_email %></td>
        <td><%= letter_request.student_application_id %></td>
        <td><%= letter_request.access_code %></td>
        <td><%= link_to 'Show', letter_request %></td>
        <td><%= link_to 'Edit', edit_letter_request_path(letter_request) %></td>
        <td><%= link_to 'Destroy', letter_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Letter request', new_letter_request_path %>

app/views/letter_requests/new.html.erb
<h1>New Letter Request</h1>

<%= render 'form' %>

<%= link_to 'Back', letter_requests_path %>

app/views/letter_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Professor email:</strong>
  <%= @letter_request.professor_email %>
</p>

<p>
  <strong>Student application:</strong>
  <%= @letter_request.student_application_id %>
</p>

<p>
  <strong>Access code:</strong>
  <%= @letter_request.access_code %>
</p>

<%= link_to 'Edit', edit_letter_request_path(@letter_request) %> |
<%= link_to 'Back', letter_requests_path %>