config/routes.rb
Rails.application.routes.default_url_options[:host] = 'localhost:3000'
Rails.application.routes.draw do
  resources :letter_field_inputs
  resources :letter_requests
  resources :form_field_inputs
  resources :form_text_inputs
  resources :form_field_values
  resources :form_fields
  resources :form_templates
  resources :student_applications
  resources :application_processes
  get 'apply'  => 'apply#index'
  post 'apply'  => 'apply#create'
  get 'apply/:application_process_id/new'  => 'apply#new', as: :apply_to
  get 'letter_requests/fill/:access_code'  => 'letter_requests#fill', as: :fill_letter

end

app/controllers/application_processes_controller.rb
class ApplicationProcessesController < ApplicationController
  before_action :set_application_process, only: [:show, :edit, :update, :destroy]

  # GET /application_processes
  # GET /application_processes.json
  def index
    @application_processes = ApplicationProcess.all
  end

  # GET /application_processes/1
  # GET /application_processes/1.json
  def show
  end

  # GET /application_processes/new
  def new
    @application_process = ApplicationProcess.new
  end

  # GET /application_processes/1/edit
  def edit
  end

  # POST /application_processes
  # POST /application_processes.json
  def create
    @application_process = ApplicationProcess.new(application_process_params)

    respond_to do |format|
      if @application_process.save
        format.html { redirect_to @application_process, notice: 'Application process was successfully created.' }
        format.json { render :show, status: :created, location: @application_process }
      else
        format.html { render :new }
        format.json { render json: @application_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /application_processes/1
  # PATCH/PUT /application_processes/1.json
  def update
    respond_to do |format|
      if @application_process.update(application_process_params)
        format.html { redirect_to @application_process, notice: 'Application process was successfully updated.' }
        format.json { render :show, status: :ok, location: @application_process }
      else
        format.html { render :edit }
        format.json { render json: @application_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_processes/1
  # DELETE /application_processes/1.json
  def destroy
    @application_process.destroy
    respond_to do |format|
      format.html { redirect_to application_processes_url, notice: 'Application process was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_process
      @application_process = ApplicationProcess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_process_params
      params.require(:application_process).permit(:name, :semester, :year, :start_date, :end_date, :form_template_id, :letter_template_id, :max_letters, :min_letters, student_applications_attributes: [:id, :name])
    end
end

app/helpers/application_processes_helper.rb
module ApplicationProcessesHelper
end

app/views/application_processes/_form.html.erb
<%= simple_form_for @application_process do |f| %>
    <%= f.input :name %>
    <%= f.input :semester, collection: 1..2, include_blank: false %>
    <%= f.input :year, collection: 1960..2100, selected: Date.today.year %>
    <%= f.input :start_date %>
    <%= f.input :end_date%>
    <%= f.association :form_template, :as => :collection_select, collection: FormTemplate.where('is_letter ==?', false), include_blank: false %>
    <%= f.association :letter_template, :as => :collection_select, collection: FormTemplate.where('is_letter ==?', true), include_blank: false  %>
    <%= f.input :min_letters %>
    <%= f.input :max_letters %>
    <%= f.button :submit %>
<% end %>

app/views/application_processes/edit.html.erb
<h1>Editing Application Process</h1>

<%= render 'form' %>

<%= link_to 'Show', @application_process %> |
<%= link_to 'Back', application_processes_path %>

app/views/application_processes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Application Processes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Semester</th>
      <th>Year</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Form template</th>
      <th>Letter template</th>
      <th>Min/Max letters</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @application_processes.each do |application_process| %>
      <tr>
        <td><%= application_process.name %></td>
        <td><%= application_process.semester %></td>
        <td><%= application_process.year %></td>
        <td><%= application_process.start_date %></td>
        <td><%= application_process.end_date %></td>
        <td><%= application_process.form_template.name %></td>
        <td><%= application_process.letter_template.name %></td>
        <td><%= application_process.min_letters %>/<%= application_process.max_letters %></td>
        <td><%= link_to 'Show', application_process %></td>
        <td><%= link_to 'Edit', edit_application_process_path(application_process) %></td>
        <td><%= link_to 'Destroy', application_process, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application process', new_application_process_path %>

app/views/application_processes/new.html.erb
<h1>New Application Process</h1>

<%= render 'form' %>

<%= link_to 'Back', application_processes_path %>

app/views/application_processes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @application_process.name %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @application_process.semester %>
</p>

<p>
  <strong>Year:</strong>
  <%= @application_process.year %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @application_process.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @application_process.end_date %>
</p>

<p>
  <strong>Form template:</strong>
  <%= @application_process.form_template.name%>
</p>

<p>
  <strong>Letter template:</strong>
  <%= @application_process.letter_template.name %>
</p>

<p>
  <strong>Min/Max letters:</strong>
  <%= @application_process.min_letters %>/
  <%= @application_process.max_letters %>
</p>

<%= link_to 'Edit', edit_application_process_path(@application_process) %> |
<%= link_to 'Back', application_processes_path %>