config/routes.rb
Rails.application.routes.default_url_options[:host] = 'localhost:3000'
Rails.application.routes.draw do
  resources :letter_field_inputs
  resources :letter_requests
  resources :form_field_inputs
  resources :form_text_inputs
  resources :form_field_values
  resources :form_fields
  resources :form_templates
  resources :student_applications
  resources :application_processes
  get 'apply'  => 'apply#index'
  post 'apply'  => 'apply#create'
  get 'apply/:application_process_id/new'  => 'apply#new', as: :apply_to
  get 'letter_requests/fill/:access_code'  => 'letter_requests#fill', as: :fill_letter

end

app/models/form_field_input.rb
class FormFieldInput < ActiveRecord::Base
  belongs_to :student_application
  belongs_to :form_field
end

app/controllers/form_field_inputs_controller.rb
class FormFieldInputsController < ApplicationController
  before_action :set_form_field_input, only: [:show, :edit, :update, :destroy]

  # GET /form_field_inputs
  # GET /form_field_inputs.json
  def index
    @form_field_inputs = FormFieldInput.all
    @form_text_inputs = FormTextInput.all

  end

  # GET /form_field_inputs/1
  # GET /form_field_inputs/1.json
  def show
  end

  # GET /form_field_inputs/new
  def new
    @form_field_input = FormFieldInput.new
  end

  # GET /form_field_inputs/1/edit
  def edit
  end

  # POST /form_field_inputs
  # POST /form_field_inputs.json
  def create
    @form_field_input = FormFieldInput.new(form_field_input_params)

    respond_to do |format|
      if @form_field_input.save
        format.html { redirect_to @form_field_input, notice: 'Form field input was successfully created.' }
        format.json { render :show, status: :created, location: @form_field_input }
      else
        format.html { render :new }
        format.json { render json: @form_field_input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_field_inputs/1
  # PATCH/PUT /form_field_inputs/1.json
  def update
    respond_to do |format|
      if @form_field_input.update(form_field_input_params)
        format.html { redirect_to @form_field_input, notice: 'Form field input was successfully updated.' }
        format.json { render :show, status: :ok, location: @form_field_input }
      else
        format.html { render :edit }
        format.json { render json: @form_field_input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_field_inputs/1
  # DELETE /form_field_inputs/1.json
  def destroy
    @form_field_input.destroy
    respond_to do |format|
      format.html { redirect_to form_field_inputs_url, notice: 'Form field input was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_field_input
      @form_field_input = FormFieldInput.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_field_input_params
      params.require(:form_field_input).permit(:student_application_id, :form_field_id, :input)
    end
end

app/helpers/form_field_inputs_helper.rb
module FormFieldInputsHelper
end

app/views/form_field_inputs/_form.html.erb
<%= form_for(@form_field_input) do |f| %>
  <% if @form_field_input.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form_field_input.errors.count, "error") %> prohibited this form_field_input from being saved:</h2>

      <ul>
      <% @form_field_input.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_application_id %><br>
    <%= f.number_field :student_application_id %>
  </div>
  <div class="field">
    <%= f.label :form_field_id %><br>
    <%= f.number_field :form_field_id %>
  </div>
  <div class="field">
    <%= f.label :input %><br>
    <%= f.text_field :input %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/form_field_inputs/edit.html.erb
<h1>Editing Form Field Input</h1>

<%= render 'form' %>

<%= link_to 'Show', @form_field_input %> |
<%= link_to 'Back', form_field_inputs_path %>

app/views/form_field_inputs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Form Field Inputs</h1>

<table>
  <thead>
    <tr>
      <th>Process </th>
      <th>Student </th>
      <th>Form field</th>
      <th>Field type</th>
      <th>Input</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @form_field_inputs.each do |form_field_input| %>
      <tr>
        <% if StudentApplication.exists?(form_field_input.student_application_id) %>
            <td><%= form_field_input.student_application.application_process.name %></td>
            <td><%= form_field_input.student_application.student_name %></td>
        <% else %>
            <td> EXCLUIDO </td><td> EXCLUIDO </td>
        <% end %>
        <td><%= form_field_input.form_field.name %></td>
        <td><%= form_field_input.form_field.field_type %></td>
        <td><%= form_field_input.input %></td>
        <td><%= link_to 'Destroy', form_field_input, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% @form_text_inputs.each do |form_text_inputs| %>
      <tr>
        <td><%= form_text_inputs.student_application.application_process.name %></td>
        <td><%= form_text_inputs.student_application.student_name %></td>
        <td><%= form_text_inputs.form_field.name %></td>
        <td><%= form_text_inputs.form_field.field_type %></td>
        <td><%= form_text_inputs.input %></td>
        <td><%= link_to 'Destroy', form_text_inputs, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>

  </tbody>
</table>


<br>

<%= link_to 'New Form field input', new_form_field_input_path %>

app/views/form_field_inputs/new.html.erb
<h1>New Form Field Input</h1>

<%= render 'form' %>

<%= link_to 'Back', form_field_inputs_path %>

app/views/form_field_inputs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student application:</strong>
  <%= @form_field_input.student_application_id %>
</p>

<p>
  <strong>Form field:</strong>
  <%= @form_field_input.form_field_id %>
</p>

<p>
  <strong>Input:</strong>
  <%= @form_field_input.input %>
</p>

<%= link_to 'Edit', edit_form_field_input_path(@form_field_input) %> |
<%= link_to 'Back', form_field_inputs_path %>