config/routes.rb
Rails.application.routes.default_url_options[:host] = 'localhost:3000'
Rails.application.routes.draw do
  resources :letter_field_inputs
  resources :letter_requests
  resources :form_field_inputs
  resources :form_text_inputs
  resources :form_field_values
  resources :form_fields
  resources :form_templates
  resources :student_applications
  resources :application_processes
  get 'apply'  => 'apply#index'
  post 'apply'  => 'apply#create'
  get 'apply/:application_process_id/new'  => 'apply#new', as: :apply_to
  get 'letter_requests/fill/:access_code'  => 'letter_requests#fill', as: :fill_letter

end

app/models/student_application.rb
class StudentApplication < ActiveRecord::Base
  belongs_to :application_process
  has_many :form_field_inputs, :dependent => :delete_all
  has_many :form_text_inputs, :dependent => :delete_all
  has_many :letter_requests, :dependent => :delete_all
  has_many :form_file_uploads, :dependent => :delete_all

  accepts_nested_attributes_for :form_field_inputs,
                                allow_destroy: true
  accepts_nested_attributes_for :letter_requests,
                                allow_destroy: true
  accepts_nested_attributes_for :form_text_inputs,
                                allow_destroy: true
  accepts_nested_attributes_for :form_file_uploads,
                                allow_destroy: true

end

app/controllers/student_applications_controller.rb
class StudentApplicationsController < ApplicationController
  before_action :set_student_application, only: [:show, :edit, :update, :destroy]

  # GET /student_applications
  # GET /student_applications.json
  def index
    @student_applications = StudentApplication.all
  end

  # GET /student_applications/1
  # GET /student_applications/1.json
  def show
  end

  # GET /student_applications/new
  def new
    @student_application = StudentApplication.new
  end

  # GET /student_applications/1/edit
  def edit
  end

  # POST /student_applications
  # POST /student_applications.json
  def create
    @student_application = StudentApplication.new(student_application_params)
    @student_application.letter_requests.each do |lr|
      lr.class
    end

    respond_to do |format|
      if @student_application.save
        @student_application.letter_requests.each do |lr|
          ApplyMailer.letter_request_mail(lr).deliver_later
        end
        format.html { redirect_to @student_application, notice: 'Student application was successfully created.' }
        format.json { render :show, status: :created, location: @student_application }
      else
        format.html { render :new }
        format.json { render json: @student_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_applications/1
  # PATCH/PUT /student_applications/1.json
  def update
    respond_to do |format|
      if @student_application.update(student_application_params)
        format.html { redirect_to @student_application, notice: 'Student application was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_application }
      else
        format.html { render :edit }
        format.json { render json: @student_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_applications/1
  # DELETE /student_applications/1.json
  def destroy
    @student_application.destroy
    respond_to do |format|
      format.html { redirect_to student_applications_url, notice: 'Student application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_application
      @student_application = StudentApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_application_params
      params.require(:student_application).permit(:student_name, :application_process_id,
                                                  form_field_inputs_attributes:[:id, :form_field_id, :input, :_destroy],
                                                  form_text_inputs_attributes:[:id, :form_field_id, :input, :_destroy],
                                                  form_file_uploads_attributes:[:id, :student_application_id, :form_field_id, :file, :_destroy],
                                                  letter_requests_attributes:[:id, :professor_email, :student_application_id, :access_code, :is_filled, :_destroy]
      )
    end
end

app/helpers/student_applications_helper.rb
module StudentApplicationsHelper
end

app/views/student_applications/_form.html.haml
= simple_form_for @student_application do |f|
  = f.input :student_name
  = f.association :application_process, as: :collection_select, include_blank: false
  = f.submit

app/views/student_applications/apply.html.haml
%h1 Apply for =

app/views/student_applications/edit.html.erb
<h1>Editing Student Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_application %> |
<%= link_to 'Back', student_applications_path %>

app/views/student_applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Student Applications</h1>

<table>
  <thead>
    <tr>
      <th>Student name</th>
      <th>Application process</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_applications.each do |student_application| %>
      <tr>
        <td><%= student_application.student_name %></td>
        <td><%= student_application.application_process_id %></td>
        <td><%= link_to 'Show', student_application %></td>
        <td><%= link_to 'Edit', edit_student_application_path(student_application) %></td>
        <td><%= link_to 'Destroy', student_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student application', new_student_application_path %>

app/views/student_applications/new.html.erb
<h1>New Student Application</h1>

<%= render 'form' %>

<%= link_to 'Back', student_applications_path %>

app/views/student_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student name:</strong>
  <%= @student_application.student_name %>
</p>

<p>
  <strong>Application process:</strong>
  <%= @student_application.application_process_id %>
</p>

<%= link_to 'Edit', edit_student_application_path(@student_application) %> |
<%= link_to 'Back', student_applications_path %>